insert into ps_dw.appliance values	(	1	,	'Space heater'	,	28	)	;
insert into ps_dw.appliance values	(	2	,	'Steam mop'	,	36	)	;
insert into ps_dw.appliance values	(	3	,	'Stove'	,	40	)	;
insert into ps_dw.appliance values	(	4	,	'Sump pump'	,	47	)	;
insert into ps_dw.appliance values	(	5	,	'Telephone'	,	25	)	;
insert into ps_dw.appliance values	(	6	,	'Television'	,	35	)	;
insert into ps_dw.appliance values	(	7	,	'Tie press'	,	33	)	;
insert into ps_dw.appliance values	(	8	,	'Toaster and toaster ovens'	,	46	)	;
insert into ps_dw.appliance values	(	9	,	'Trouser press'	,	38	)	;
insert into ps_dw.appliance values	(	10	,	'Vacuum cleaner'	,	29	)	;
insert into ps_dw.appliance values	(	11	,	'Manual vacuum cleaner'	,	37	)	;
insert into ps_dw.appliance values	(	12	,	'Robotic vacuum cleaner'	,	36	)	;
insert into ps_dw.appliance values	(	13	,	'Washing machine'	,	29	)	;
insert into ps_dw.appliance values	(	14	,	'Water cooker'	,	35	)	;
insert into ps_dw.appliance values	(	15	,	'Water purifier'	,	40	)	;
insert into ps_dw.appliance values	(	16	,	'Water heater'	,	38	)	;
insert into ps_dw.appliance values	(	17	,	'Solar water heater'	,	25	)	;
insert into ps_dw.appliance values	(	18	,	'Window fan'	,	41	)	;
insert into ps_dw.appliance values	(	19	,	'Waffle iron'	,	43	)	;
insert into ps_dw.appliance values	(	20	,	'Icebox'	,	47	)	;
insert into ps_dw.appliance values	(	21	,	'Kimchi refrigerator'	,	32	)	;
insert into ps_dw.appliance values	(	22	,	'Light fixture'	,	44	)	;
insert into ps_dw.appliance values	(	23	,	'Light'	,	32	)	;
insert into ps_dw.appliance values	(	24	,	'Mangle (machine)'	,	44	)	;
insert into ps_dw.appliance values	(	25	,	'Meat grinder'	,	30	)	;
insert into ps_dw.appliance values	(	26	,	'Micathermic heater'	,	37	)	;
insert into ps_dw.appliance values	(	27	,	'Microwave oven'	,	33	)	;
insert into ps_dw.appliance values	(	28	,	'Mobile charger'	,	38	)	;
insert into ps_dw.appliance values	(	29	,	'Mousetrap'	,	34	)	;
insert into ps_dw.appliance values	(	30	,	'MP3 player'	,	43	)	;
insert into ps_dw.appliance values	(	31	,	'Nightlight'	,	46	)	;
insert into ps_dw.appliance values	(	32	,	'Oil heater'	,	36	)	;
insert into ps_dw.appliance values	(	33	,	'Oven'	,	49	)	;
insert into ps_dw.appliance values	(	34	,	'Patio heater'	,	44	)	;
insert into ps_dw.appliance values	(	35	,	'Paper shredder'	,	42	)	;
insert into ps_dw.appliance values	(	36	,	'Radiator (heating)'	,	40	)	;
insert into ps_dw.appliance values	(	37	,	'Radio receiver'	,	45	)	;
insert into ps_dw.appliance values	(	38	,	'Refrigerator'	,	39	)	;
insert into ps_dw.appliance values	(	39	,	'Internet refrigerator'	,	32	)	;
insert into ps_dw.appliance values	(	40	,	'Thermal mass refrigerator'	,	31	)	;
insert into ps_dw.appliance values	(	41	,	'Sewing machine'	,	49	)	;
insert into ps_dw.appliance values	(	42	,	'Space heater'	,	36	)	;
insert into ps_dw.appliance values	(	43	,	'Steam mop'	,	27	)	;
insert into ps_dw.appliance values	(	44	,	'Stove'	,	36	)	;
insert into ps_dw.appliance values	(	45	,	'Sump pump'	,	26	)	;
insert into ps_dw.appliance values	(	46	,	'Telephone'	,	31	)	;
insert into ps_dw.appliance values	(	47	,	'Television'	,	44	)	;
insert into ps_dw.appliance values	(	48	,	'Tie press'	,	46	)	;
insert into ps_dw.appliance values	(	49	,	'Toaster and toaster ovens'	,	38	)	;
insert into ps_dw.appliance values	(	50	,	'Trouser press'	,	50	)	;
insert into ps_dw.appliance values	(	51	,	'Vacuum cleaner'	,	50	)	;
insert into ps_dw.appliance values	(	52	,	'Manual vacuum cleaner'	,	43	)	;
insert into ps_dw.appliance values	(	53	,	'Robotic vacuum cleaner'	,	46	)	;
insert into ps_dw.appliance values	(	54	,	'Washing machine'	,	35	)	;
insert into ps_dw.appliance values	(	55	,	'Water cooker'	,	40	)	;
insert into ps_dw.appliance values	(	56	,	'Water purifier'	,	25	)	;
insert into ps_dw.appliance values	(	57	,	'Water heater'	,	32	)	;
insert into ps_dw.appliance values	(	58	,	'Solar water heater'	,	44	)	;
insert into ps_dw.appliance values	(	59	,	'Window fan'	,	30	)	;
insert into ps_dw.appliance values	(	60	,	'Waffle iron'	,	44	)	;
insert into ps_dw.appliance values	(	61	,	'Computer'	,	28	)	;
insert into ps_dw.appliance values	(	62	,	'Digital camera'	,	41	)	;
insert into ps_dw.appliance values	(	63	,	'Dish draining closet'	,	36	)	;
insert into ps_dw.appliance values	(	64	,	'Dishwasher'	,	48	)	;
insert into ps_dw.appliance values	(	65	,	'Drawer dishwasher'	,	27	)	;
insert into ps_dw.appliance values	(	66	,	'DVD player'	,	49	)	;
insert into ps_dw.appliance values	(	67	,	'Electric water boiler'	,	37	)	;
insert into ps_dw.appliance values	(	68	,	'Evaporative cooler'	,	25	)	;
insert into ps_dw.appliance values	(	69	,	'Exhaust hood'	,	32	)	;
insert into ps_dw.appliance values	(	70	,	'Fan heater'	,	47	)	;
insert into ps_dw.appliance values	(	71	,	'Flame supervision device'	,	26	)	;
insert into ps_dw.appliance values	(	72	,	'Forced-air'	,	46	)	;
insert into ps_dw.appliance values	(	73	,	'Futon dryer'	,	41	)	;
insert into ps_dw.appliance values	(	74	,	'Garbage disposal unit'	,	34	)	;
insert into ps_dw.appliance values	(	75	,	'Gas appliance'	,	26	)	;
insert into ps_dw.appliance values	(	76	,	'Go-to-bed matchbox'	,	45	)	;
insert into ps_dw.appliance values	(	77	,	'Hair dryer'	,	28	)	;
insert into ps_dw.appliance values	(	78	,	'Hair iron'	,	40	)	;
insert into ps_dw.appliance values	(	79	,	'Hob (hearth)'	,	34	)	;
insert into ps_dw.appliance values	(	80	,	'Home server'	,	30	)	;
insert into ps_dw.appliance values	(	81	,	'Humidifier'	,	42	)	;
insert into ps_dw.appliance values	(	82	,	'HVAC'	,	39	)	;
insert into ps_dw.appliance values	(	83	,	'Icebox'	,	48	)	;
insert into ps_dw.appliance values	(	84	,	'Kimchi refrigerator'	,	41	)	;
insert into ps_dw.appliance values	(	85	,	'Light fixture'	,	47	)	;
insert into ps_dw.appliance values	(	86	,	'Light'	,	27	)	;
insert into ps_dw.appliance values	(	87	,	'Mangle (machine)'	,	31	)	;
insert into ps_dw.appliance values	(	88	,	'Meat grinder'	,	40	)	;
insert into ps_dw.appliance values	(	89	,	'Micathermic heater'	,	38	)	;
insert into ps_dw.appliance values	(	90	,	'Microwave oven'	,	43	)	;
insert into ps_dw.appliance values	(	91	,	'Mobile charger'	,	37	)	;
insert into ps_dw.appliance values	(	92	,	'Mousetrap'	,	44	)	;
insert into ps_dw.appliance values	(	93	,	'MP3 player'	,	50	)	;
insert into ps_dw.appliance values	(	94	,	'Nightlight'	,	39	)	;
insert into ps_dw.appliance values	(	95	,	'Oil heater'	,	46	)	;
insert into ps_dw.appliance values	(	96	,	'Oven'	,	29	)	;
insert into ps_dw.appliance values	(	97	,	'Patio heater'	,	26	)	;
insert into ps_dw.appliance values	(	98	,	'Paper shredder'	,	27	)	;
insert into ps_dw.appliance values	(	99	,	'Radiator (heating)'	,	26	)	;
insert into ps_dw.appliance values	(	100	,	'Radio receiver'	,	37	)	;
insert into ps_dw.appliance values	(	101	,	'Refrigerator'	,	50	)	;
insert into ps_dw.appliance values	(	102	,	'Internet refrigerator'	,	38	)	;
insert into ps_dw.appliance values	(	103	,	'Thermal mass refrigerator'	,	50	)	;
insert into ps_dw.appliance values	(	104	,	'Sewing machine'	,	33	)	;
insert into ps_dw.appliance values	(	105	,	'Space heater'	,	46	)	;
insert into ps_dw.appliance values	(	106	,	'Steam mop'	,	32	)	;
insert into ps_dw.appliance values	(	107	,	'Stove'	,	44	)	;
insert into ps_dw.appliance values	(	108	,	'Sump pump'	,	29	)	;
insert into ps_dw.appliance values	(	109	,	'Telephone'	,	46	)	;
insert into ps_dw.appliance values	(	110	,	'Television'	,	41	)	;
insert into ps_dw.appliance values	(	111	,	'Tie press'	,	34	)	;
insert into ps_dw.appliance values	(	112	,	'Toaster and toaster ovens'	,	30	)	;
insert into ps_dw.appliance values	(	113	,	'Trouser press'	,	48	)	;
insert into ps_dw.appliance values	(	114	,	'Vacuum cleaner'	,	36	)	;
insert into ps_dw.appliance values	(	115	,	'Manual vacuum cleaner'	,	40	)	;
insert into ps_dw.appliance values	(	116	,	'Robotic vacuum cleaner'	,	50	)	;
insert into ps_dw.appliance values	(	117	,	'Washing machine'	,	33	)	;
insert into ps_dw.appliance values	(	118	,	'Water cooker'	,	26	)	;
insert into ps_dw.appliance values	(	119	,	'Water purifier'	,	40	)	;
insert into ps_dw.appliance values	(	120	,	'Water heater'	,	41	)	;
insert into ps_dw.appliance values	(	121	,	'Solar water heater'	,	34	)	;
insert into ps_dw.appliance values	(	122	,	'Window fan'	,	43	)	;
insert into ps_dw.appliance values	(	123	,	'Waffle iron'	,	47	)	;
insert into ps_dw.appliance values	(	124	,	'Air conditioner'	,	31	)	;
insert into ps_dw.appliance values	(	125	,	'Air ioniser'	,	40	)	;
insert into ps_dw.appliance values	(	126	,	'Air purifier'	,	30	)	;
insert into ps_dw.appliance values	(	127	,	'Appliance plug'	,	43	)	;
insert into ps_dw.appliance values	(	128	,	'Aroma lamp'	,	37	)	;
insert into ps_dw.appliance values	(	129	,	'Attic fan'	,	35	)	;
insert into ps_dw.appliance values	(	130	,	'Bachelor griller'	,	49	)	;
insert into ps_dw.appliance values	(	131	,	'Bed side lamp'	,	34	)	;
insert into ps_dw.appliance values	(	132	,	'Back boiler'	,	38	)	;
insert into ps_dw.appliance values	(	133	,	'Beverage opener'	,	39	)	;
insert into ps_dw.appliance values	(	134	,	'Blender'	,	29	)	;
insert into ps_dw.appliance values	(	135	,	'Box mangle'	,	33	)	;
insert into ps_dw.appliance values	(	136	,	'Camcorder'	,	30	)	;
insert into ps_dw.appliance values	(	137	,	'Can opener'	,	27	)	;
insert into ps_dw.appliance values	(	138	,	'Ceiling fan'	,	37	)	;
insert into ps_dw.appliance values	(	139	,	'Central vacuum cleaner'	,	49	)	;
insert into ps_dw.appliance values	(	140	,	'Clothes dryer'	,	35	)	;
insert into ps_dw.appliance values	(	141	,	'Clothes iron'	,	47	)	;
insert into ps_dw.appliance values	(	142	,	'Coffee grinder'	,	25	)	;
insert into ps_dw.appliance values	(	143	,	'Cold-pressed juicer'	,	45	)	;
insert into ps_dw.appliance values	(	144	,	'Combo washer dryer'	,	43	)	;
insert into ps_dw.appliance values	(	145	,	'Comparison of domestic robots'	,	38	)	;
insert into ps_dw.appliance values	(	146	,	'Central vacuum cleaner'	,	49	)	;
insert into ps_dw.appliance values	(	147	,	'Space dryer'	,	35	)	;
insert into ps_dw.appliance values	(	148	,	'Room Heater Variant-X'	,	47	)	;
insert into ps_dw.appliance values	(	149	,	'Coffee Spicer'	,	25	)	;
insert into ps_dw.appliance values	(	150	,	'Cold Juicer'	,	45	)	;
insert into ps_dw.appliance values	(	151	,	'Big dryer'	,	43	)	;
insert into ps_dw.appliance values	(	152	,	'Robo Maker'	,	38	)	;